package frgp.utn.edu.ar.controllers.utils;

public enum LogsEnum {
    LOGIN,
    LOGOUT,
    MODIFICAR_USUARIO,
    REGISTRO_USUARIO,
    BLOQUEO_USUARIO,
    DESBLOQUEO_USUARIO,
    RECUPERO_PASS,
    CAMBIO_PASS,
    CREACION_REPORTE,
    SOLICITUD_CIERRE_REPORTE,
    CIERRE_REPORTE,
    REAPERTURA_REPORTE,
    VALORAR_REPORTE,
    DENUNCIA_REPORTE
}
